// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhouwzuvxjvepschzldc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxob3V3enV2eGp2ZXBzY2h6bGRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzYwMTAsImV4cCI6MjA3MDUxMjAxMH0.iYmzNJyZdCtIhX2bhnJB9klbknpjJx2ejhxES6dAGe8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});